# Generated by Django 5.2.6 on 2025-10-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together={('list', 'restaurant')},
        ),
    ]
