# Generated by Django 5.2.6 on 2025-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_pin_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AddField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
