# Generated by Django 5.2.6 on 2025-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='would_go_again',
            field=models.BooleanField(default=True, help_text='Would you go again?'),
        ),
    ]
