# Generated by Django 5.2.6 on 2025-10-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_review_would_go_again'),
        ('social', '0007_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_cuisines',
            field=models.JSONField(blank=True, default=list, help_text='List of favorite cuisine types'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_spots',
            field=models.ManyToManyField(blank=True, limit_choices_to={'id__in': []}, related_name='favorite_of', to='places.restaurant'),
        ),
    ]
